version: '3.8'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    # environment:
    #   POSTGRES_USER: postgres
    #   POSTGRES_PASSWORD: postgres
    #   POSTGRES_DB: event
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  postgres-data:
